#include "${name}.h"

// This file was autogenerated by cerverpages.py
// You may customize this file however you like.
// This file will not be overwritten by cerverpages.py

${name}::${name}() {}
${name}::~${name}() {} 
void ${name}::init () {
	//_cgi = cgiInit();
}
void ${name}::shutdown () {}




