#ifndef ___${upname}_H
#define ___${upname}_H

// This file was autogenerated by gencp
// You may customize this file however you like.
// This file will not be overwritten by gencp
void ${name}_init ();
void ${name}_docgi (); 
void ${name}_shutdown ();

#endif // ___${upname}_H
