#include <stdio.h>
#include "${name}.h"

// This file was autogenerated by cerverpages.py
// DO NOT EDIT this file
// This file will be overwritten by cerverpages.py

void ${name}_init () {
}

void ${name}_docgi ()
{
	puts ("Content-type: text/html\n");
	${i:docgi.tmp}
}

void ${name}_shutdown () {
}

int main (int argc, char *argv[])
{
				${name}_init();
				${name}_docgi();
				${name}_shutdown();
				return 0;
}
