#include <stdio.h>
#include "${name}.h"

// This file was autogenerated by cerverpages.py
// DO NOT EDIT this file
// This file will be overwritten by cerverpages.py



void ${name}::docgi ()
{
	puts ("Content-type: text/html\n");
	${i:docgi.tmp}
}

int main (int argc, char *argv[])
{
				${name} ${name};
				${name}.init();
				${name}.docgi();
				${name}.shutdown();
}
