#ifndef ___${upname}_H
#define ___${upname}_H

//#include <cgi.h>
#include "cerverpages.h"

// This file was autogenerated by cerverpages.py
// You may customize this file however you like.
// This file will not be overwritten by cerverpages.py

class ${name}:public CerverPages {
protected:
	//s_cgi* _cgi;
public:
	${name}();
  ~${name}(); 
	void init ();
	void docgi (); 
	void shutdown ();
};

#endif // ___${upname}_H
