#include <stdio.h>

// This file was autogenerated by gencp
// DO NOT EDIT this file
// This file will be overwritten by gencp

static char* contentType = "text/html";

${top}

void startup () {
	//_cgi = cgiInit();
${startup}
}

void do_contentType() {
	fprintf(stdout, "Content-type: %s\n\n", contentType);
}
void docgi ()
{
${cgi}
}

void shutdown () {
${shutdown}
}

int main (int argc, char *argv[])
{
				startup();
				do_contentType();
				docgi();
				shutdown();
				return 0;
}




