#include "${name}.h"

// This file was autogenerated by gencp
// You may customize this file however you like.
// This file will not be overwritten by gencp

void ${name}_init () {
	//_cgi = cgiInit();
}
void ${name}_shutdown () {
}




